on: [push, pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: RefDiff
        id: ref-diff
        uses: rodrigo-brito/refdiff-github-action@master
